import 'dart:convert';
import 'dart:io';

const _sourcePath = 'tool/source/quran-uthmani.json';

// Arabic tatweel, harakat/tanween, superscript alef, and Quranic
// annotation marks -- stripped before comparing words.
final _diacritics =
    RegExp(r'[ـً-ٰٟۖ-ۭ]');

String _normalize(String word) => word.replaceAll(_diacritics, '');

void main() {
  final source = File(_sourcePath);
  if (!source.existsSync()) {
    stderr.writeln('Missing $_sourcePath — download it first (see plan).');
    exit(1);
  }
  final root = jsonDecode(source.readAsStringSync()) as Map<String, dynamic>;
  final surahs = (root['data'] as Map<String, dynamic>)['surahs'] as List;
  if (surahs.length != 114) {
    throw StateError('expected 114 suras, got ${surahs.length}');
  }

  final suraAyahCounts = <int>[];
  final rawWords = <int>[];
  final pageOfAyah = <int>[]; // 1-based mushaf page per global ayah index
  var basmalaStripped = 0;

  for (final s in surahs) {
    final suraNum = s['number'] as int;
    final ayahs = s['ayahs'] as List;
    suraAyahCounts.add(ayahs.length);
    for (final a in ayahs) {
      // Skip tokens that are only waqf/annotation marks (the Uthmani text
      // writes pause signs as standalone space-separated characters).
      var words = (a['text'] as String)
          .trim()
          .split(RegExp(r'\s+'))
          .where((w) => _normalize(w).isNotEmpty)
          .toList();
      if (a['numberInSurah'] == 1 &&
          suraNum != 1 &&
          suraNum != 9 &&
          words.length > 4 &&
          _normalize(words.first) == 'بسم') {
        words = words.sublist(4);
        basmalaStripped++;
      }
      rawWords.add(words.length);
      pageOfAyah.add(a['page'] as int);
    }
  }

  // --- sanity checks: hard-fail on anything unexpected ---
  final totalAyahs = rawWords.length;
  if (totalAyahs != 6236) {
    throw StateError('expected 6236 ayahs, got $totalAyahs');
  }
  final totalWords = rawWords.reduce((a, b) => a + b);
  if (totalWords < 74000 || totalWords > 81000) {
    throw StateError('total word count $totalWords outside expected range');
  }
  if (basmalaStripped != 0 && basmalaStripped != 112) {
    throw StateError('basmala stripped from $basmalaStripped suras; '
        'expected 0 (source has no basmala) or 112');
  }
  for (var i = 1; i < totalAyahs; i++) {
    if (pageOfAyah[i] < pageOfAyah[i - 1]) {
      throw StateError('page numbers not monotonic at global ayah $i');
    }
  }
  if (pageOfAyah.first != 1 || pageOfAyah.last != 604) {
    throw StateError('page range is not 1..604');
  }
  if (pageOfAyah.toSet().length != 604) {
    throw StateError('some pages have no ayahs — wrong mushaf layout?');
  }
  print('source OK: $totalAyahs ayahs, $totalWords words, '
      'basmala stripped from $basmalaStripped suras');

  // --- page map: global index of the first ayah on each page ---
  final pageFirst = List<int>.filled(604, -1);
  for (var i = 0; i < totalAyahs; i++) {
    final p = pageOfAyah[i] - 1;
    if (pageFirst[p] == -1) pageFirst[p] = i;
  }

  // --- effective weights: raw words + header/basmala padding ---
  final rawPageWords = List<int>.filled(604, 0);
  for (var i = 0; i < totalAyahs; i++) {
    rawPageWords[pageOfAyah[i] - 1] += rawWords[i];
  }
  final suraFirstIndex = <int>[];
  var acc = 0;
  for (final c in suraAyahCounts) {
    suraFirstIndex.add(acc);
    acc += c;
  }
  // Sura 1: basmala IS aya 1 (header only). Sura 9: no basmala (header only).
  int decoLines(int sura) => (sura == 1 || sura == 9) ? 1 : 2;
  final decoPerPage = List<int>.filled(604, 0);
  for (var s = 1; s <= 114; s++) {
    decoPerPage[pageOfAyah[suraFirstIndex[s - 1]] - 1] += decoLines(s);
  }
  final weights = rawWords.map((w) => w.toDouble()).toList();
  for (var s = 1; s <= 114; s++) {
    final gi = suraFirstIndex[s - 1];
    final p = pageOfAyah[gi] - 1;
    // Pages 1-2 are short ornamental pages (~6 text lines); others have 15
    // lines minus the decoration lines they carry.
    final textLines = p < 2 ? 6 : 15 - decoPerPage[p];
    final wordsPerLine = rawPageWords[p] / textLines;
    weights[gi] += wordsPerLine * decoLines(s);
  }

  // --- write generated Dart constants ---
  String fmtInts(List<int> xs) => '[${xs.join(', ')}]';
  String fmtDoubles(List<double> xs) =>
      '[${xs.map((x) => x.toStringAsFixed(3)).join(', ')}]';
  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/generate_data.dart — do not edit by hand.')
    ..writeln('// Madani 604-page mushaf (Hafs). '
        'Source text: api.alquran.cloud (quran-uthmani).')
    ..writeln()
    ..writeln('const List<int> suraAyahCounts = ${fmtInts(suraAyahCounts)};')
    ..writeln()
    ..writeln('const List<int> pageFirstAyahIndex = ${fmtInts(pageFirst)};')
    ..writeln()
    ..writeln('const List<double> ayahWeights = ${fmtDoubles(weights)};');
  File('lib/src/data/quran_data.g.dart')
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(buf.toString());

  // --- write reusable JSON for servers / other languages ---
  int suraOf(int gi) {
    var s = 0;
    while (s < 113 && suraFirstIndex[s + 1] <= gi) {
      s++;
    }
    return s + 1;
  }

  Directory('data').createSync();
  File('data/page_map.json').writeAsStringSync(jsonEncode([
    for (final gi in pageFirst)
      {'sura': suraOf(gi), 'aya': gi - suraFirstIndex[suraOf(gi) - 1] + 1},
  ]));
  File('data/ayah_weights.json').writeAsStringSync(jsonEncode({
    'suraAyahCounts': suraAyahCounts,
    'pageFirstAyahIndex': pageFirst,
    'ayahWeights': weights,
  }));
  print('wrote lib/src/data/quran_data.g.dart, '
      'data/page_map.json, data/ayah_weights.json');
}
